-- AlterTable
ALTER TABLE "HeroImage" ADD COLUMN     "cropX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cropY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "zoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
