-- AlterTable
ALTER TABLE "CampaignImage" ADD COLUMN     "cropHeight" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "cropWidth" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "cropX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cropY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "zoom" DOUBLE PRECISION NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "ProductImage" ADD COLUMN     "cropHeight" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "cropWidth" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "cropX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cropY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "zoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
