-- AlterTable
ALTER TABLE "Collection" ADD COLUMN     "altText" TEXT,
ADD COLUMN     "desktopCropHeight" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "desktopCropMode" TEXT NOT NULL DEFAULT 'auto',
ADD COLUMN     "desktopCropWidth" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "desktopCropX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "desktopCropY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "desktopZoom" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "mobileCropHeight" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "mobileCropMode" TEXT NOT NULL DEFAULT 'auto',
ADD COLUMN     "mobileCropWidth" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "mobileCropX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "mobileCropY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "mobileZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
